#!/usr/bin/env bash

# i3 repo
if [ ! -f /etc/apt/sources.list.d/sur5r-i3.list ]
then
    tmp_dir=~/tmp
    mkdir -p "${tmp_dir}"
    /usr/lib/apt/apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2019.02.01_all.deb "${tmp_dir}/keyring.deb" SHA256:176af52de1a976f103f9809920d80d02411ac5e763f695327de9fa6aff23f416
    sudo dpkg -i "${tmp_dir}/keyring.deb"
    echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | (sudo bash -c 'cat > /etc/apt/sources.list.d/sur5r-i3.list')
    rm -f "${tmp_dir}/keyring.deb"
fi


