#!/usr/bin/env bash

# Microsoft repo
if [ ! -f /etc/apt/sources.list.d/vscode.list ]
then
    ensure-packages-installed gpg
    ensure-packages-installed software-properties-common apt-transport-https wget
    mkdir -p ~/tmp
    curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > ~/tmp/microsoft.gpg
    sudo install -o root -g root -m 644 ~/tmp/microsoft.gpg /usr/share/keyrings/
    sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    xdg-mime default code.desktop text/plain
fi

